import { RawData } from "$/lib/context";

export const dummyData: RawData = [
  {
    Name: "🎓 American University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024",
    Notes: "In the afternoon (Eastern Time)",
  },
  {
    Name: "🎓 Amherst College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 6:21 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Amherst College",
    Tag: "RD",
    Confirmed: "Approximate",
    "Decision Date": "March 20, 2025 6:21 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Babson College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Babson College",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 8, 2025 4:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Barnard College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 14, 2024",
    Notes: "In the evening (Eastern Time)",
  },
  {
    Name: "🎓 Barnard College",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 26, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Bates College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 14, 2024 12:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Bentley University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 15, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Boston College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 3, 2024 6:00 PM (EST)",
    Notes: "Approx. time",
  },
  {
    Name: "🎓 Boston University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 5:00 PM (EST)",
    Notes: "Approx. time",
  },
  {
    Name: "🎓 Bowdoin College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Bowdoin College",
    Tag: "ED 2",
    Confirmed: "Speculated",
    "Decision Date": "February 7, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Bowdoin College",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Brandeis University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Brown University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Brown University",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Bryn Mawr College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 4:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Caltech",
    Tag: "REA/SCEA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 8:48 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Carleton College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 8:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Carnegie Mellon University (CMU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 4:00 PM (EST)",
    Notes: "Until December 15th",
  },
  {
    Name: "🎓 Case Western Reserve University (CWRU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 7, 2024 12:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Case Western Reserve University (CWRU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024 8:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Case Western Reserve University (CWRU)",
    Tag: "ED 2",
    Confirmed: "Approximate",
    "Decision Date": "February 10, 2025 9:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Case Western Reserve University (CWRU)",
    Tag: "RD",
    Confirmed: "Approximate",
    "Decision Date": "March 22, 2025 9:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Catholic University of America",
    Tag: "ED EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 16, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Chapman University",
    Tag: "ED EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Claremont McKenna College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 8:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Clark University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Clemson University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Colby College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Colgate University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 College of Charleston",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024",
    Notes: "",
  },
  {
    Name: "🎓 College of the Holy Cross",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Colorado College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 11, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Colorado College",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024 3:00 PM (PST)",
    Notes: "",
  },
  {
    Name: "🎓 Colorado College",
    Tag: "ED 2",
    Confirmed: "Confirmed",
    "Decision Date": "February 13, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Colorado College",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 13, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Columbia University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 18, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Columbia University",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Connecticut College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 14, 2024 10:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Cornell University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Cornell University",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Dartmouth College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Dartmouth College",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Davidson College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 14, 2024 10:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Drexel University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024",
    Notes: "In the evening",
  },
  {
    Name: "🎓 Duke University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 16, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Emerson College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024 2:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Emerson College",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 14, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Emory University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 11, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Emory University",
    Tag: "ED 2",
    Confirmed: "Speculated",
    "Decision Date": "February 5, 2025 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Emory University",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 26, 2025 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Fairfield University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 5, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Fairfield University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 18, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Florida International University (FIU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 11, 2024",
    Notes: "In state students only",
  },
  {
    Name: "🎓 Florida International University (FIU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 22, 2025",
    Notes: "Out of state students only",
  },
  {
    Name: "🎓 Florida State University (FSU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Florida State University (FSU)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "February 13, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Fordham University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Furman University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "November 15, 2024",
    Notes: "",
  },
  {
    Name: "🎓 George Mason University (GMU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 16, 2024",
    Notes: "",
  },
  {
    Name: "🎓 George Washington University (GWU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 16, 2024",
    Notes: "In the evening (Eastern Time)",
  },
  {
    Name: "🎓 Georgetown University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 5:50 PM (EST)",
    Notes: "Appox. time",
  },
  {
    Name: "🎓 Georgetown University",
    Tag: "RD",
    Confirmed: "Approximate",
    "Decision Date": "April 1, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Georgia Tech",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 6, 2024 7:00 PM (EST)",
    Notes: "Georgia students only",
  },
  {
    Name: "🎓 Georgia Tech",
    Tag: "EA 2",
    Confirmed: "Confirmed",
    "Decision Date": "January 31, 2025",
    Notes: "Likely time: 7pm ET",
  },
  {
    Name: "🎓 Georgia Tech",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 7, 2025 7:00 PM (EST)",
    Notes: "Georgia students only",
  },
  {
    Name: "🎓 Georgia Tech",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 28, 2025 7:00 PM (EST)",
    Notes: "Out of state students only",
  },
  {
    Name: "🎓 Hamilton College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 8:00 PM (EST)",
    Notes: "By this date",
  },
  {
    Name: "🎓 Harvard University",
    Tag: "REA/SCEA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Harvard University",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Harvey Mudd College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 9:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Haverford College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Ivy Day",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Johns Hopkins University (JHU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Johns Hopkins University (JHU)",
    Tag: "ED 2",
    Confirmed: "Confirmed",
    "Decision Date": "February 14, 2025 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Johns Hopkins University (JHU)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 21, 2025 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Johns Hopkins University (JHU)",
    Tag: "Transfer",
    Confirmed: "Confirmed",
    "Decision Date": "May 9, 2025 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Lafayette College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 16, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Lehigh University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Lewis and Clark College",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 8:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Loyola Marymount University (LMU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "November 25, 2024 9:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Loyola Marymount University (LMU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Loyola University Maryland",
    Tag: "ED EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 18, 2024 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Macalester College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 8, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Macalester College",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 21, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Macalester College",
    Tag: "ED 2",
    Confirmed: "Confirmed",
    "Decision Date": "January 26, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Macalester College",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 16, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Mercer University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "November 14, 2024 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Miami University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Middlebury College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 7, 2024 8:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Middlebury College",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 15, 2025 8:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 MIT",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024 6:28 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 MIT",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 14, 2025 6:28 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 New York University (NYU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 4:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 New York University (NYU)",
    Tag: "ED 2",
    Confirmed: "Approximate",
    "Decision Date": "February 15, 2025 4:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 New York University (NYU)",
    Tag: "RD",
    Confirmed: "Approximate",
    "Decision Date": "April 1, 2025 4:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Northeastern University (NEU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 11, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Northwestern University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024",
    Notes: "Speculated time: 4pm ET",
  },
  {
    Name: "🎓 Oberlin College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Occidental College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Ohio State University (OSU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "Ohio residents and Stamps Eminence applicants only",
  },
  {
    Name: "🎓 Ohio State University (OSU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 24, 2025",
    Notes: "All non-Ohio residents and international applicants",
  },
  {
    Name: "🎓 Ohio State University (OSU)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 7, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Pepperdine University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Pitzer College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Pomona College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Princeton University",
    Tag: "REA/SCEA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Princeton University",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Providence College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 3, 2024",
    Notes: "In the evening",
  },
  {
    Name: "🎓 Providence College",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024",
    Notes: "In the evening (Eastern Time)",
  },
  {
    Name: "🎓 Purdue University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 15, 2025 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 QuestBridge Match Day",
    Tag: "QB Match",
    Confirmed: "Confirmed",
    "Decision Date": "December 2, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Quinnipiac University (QU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 5, 2024",
    Notes: "Round 1/3",
  },
  {
    Name: "🎓 Quinnipiac University (QU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024",
    Notes: "Round 2/3",
  },
  {
    Name: "🎓 Quinnipiac University (QU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024",
    Notes: "Round 3/3",
  },
  {
    Name: "🎓 Rensselaer Polytechnic Institute (RPI)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 14, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Rensselaer Polytechnic Institute (RPI)",
    Tag: "ED 2",
    Confirmed: "Confirmed",
    "Decision Date": "January 25, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Rensselaer Polytechnic Institute (RPI)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "February 1, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Rensselaer Polytechnic Institute (RPI)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 8, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Rhode Island School of Design (RISD)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Rice University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 14, 2024 10:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Rose-Hulman",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 11, 2024 3:30 PM (EST)",
    Notes: "Approx. time",
  },
  {
    Name: "🎓 Santa Clara University (SCU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 11, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Sarah Lawrence College (SLC)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Scripps College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Skidmore College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 14, 2024 10:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Smith College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 3:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Southern Methodist University (SMU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 5, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Southern Methodist University (SMU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024 8:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Spelman College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Stanford University",
    Tag: "REA/SCEA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Stanford University",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 28, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Suffolk University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Swarthmore College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Swarthmore College",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Syracuse University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 18, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Texas Christian University (TCU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 6, 2024 6:15 PM (EST)",
    Notes: "May release earlier in the day",
  },
  {
    Name: "🎓 Texas Christian University (TCU)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Trinity College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Trinity University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "November 22, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Trinity University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Tufts University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Tulane University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 3, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Tulane University",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 23, 2024 12:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 UC Berkeley",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 27, 2025",
    Notes: "",
  },
  {
    Name: "🎓 UC Davis (UCD)",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 7, 2025 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 UC Merced (UCM)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "December 18, 2024",
    Notes: "Began rolling out",
  },
  {
    Name: "🎓 UC San Diego (UCSD)",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 7:30 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 UC Santa Barbara (UCSB)",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 18, 2025 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 UCLA",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 8:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 UNC Chapel Hill",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 4:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Central Florida (UCF)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "November 15, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Chicago (UChicago)",
    Tag: "ED EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 20, 2024",
    Notes: "Approx. 4:45 PM ET",
  },
  {
    Name: "🎓 University of Denver",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 16, 2024",
    Notes: "",
  },
  {
    Name: "🎓 University of Florida (UF)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 24, 2025 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Florida (UF)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 14, 2025 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Georgia (UGA)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "November 22, 2024 4:00 PM (EST)",
    Notes: "In state students only",
  },
  {
    Name: "🎓 University of Georgia (UGA)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 6, 2024 4:00 PM (EST)",
    Notes: "Out of state students only",
  },
  {
    Name: "🎓 University of Illinois Urbana Champaign (UIUC)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 31, 2025 5:00 PM (EST)",
    Notes: "Date confirmed, time likely",
  },
  {
    Name: "🎓 University of Illinois Urbana Champaign (UIUC)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "February 28, 2025 5:00 PM (EST)",
    Notes: "Date confirmed, time likely",
  },
  {
    Name: "🎓 University of Massachusetts Amherst (UMass)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 17, 2025",
    Notes: "In the evening",
  },
  {
    Name: "🎓 University of Miami (UMiami)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "",
  },
  {
    Name: "🎓 University of Miami (UMiami)",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Michigan (UMich)",
    Tag: "EA",
    Confirmed: "Approximate",
    "Decision Date": "January 31, 2025",
    Notes: "Speculated time: 3pm ET",
  },
  {
    Name: "🎓 University of Notre Dame",
    Tag: "REA/SCEA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024 6:42 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Pennsylvania (UPenn)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Pennsylvania (UPenn)",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Richmond",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Rochester",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "In the evening (Eastern Time)",
  },
  {
    Name: "🎓 University of San Francisco (USFCA)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of South Carolina",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024",
    Notes: "In the evening (Eastern Time)",
  },
  {
    Name: "🎓 University of South Florida (USF)",
    Tag: "Priority",
    Confirmed: "Confirmed",
    "Decision Date": "December 10, 2024",
    Notes: "",
  },
  {
    Name: "🎓 University of Southern California (USC)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 17, 2025",
    Notes: "",
  },
  {
    Name: "🎓 University of Tennessee Knoxville (UTK)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 4, 2024",
    Notes: "In state only, evening of",
  },
  {
    Name: "🎓 University of Tennessee Knoxville (UTK)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024",
    Notes: "Out of state only, evening of",
  },
  {
    Name: "🎓 University of Tennessee Knoxville (UTK)",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 4, 2025",
    Notes: "Evening of",
  },
  {
    Name: "🎓 University of Vermont (UVM)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 2, 2024",
    Notes: "",
  },
  {
    Name: "🎓 University of Vermont (UVM)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "December 19, 2024 7:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Vermont (UVM)",
    Tag: "ED 2",
    Confirmed: "Confirmed",
    "Decision Date": "February 12, 2025",
    Notes: "",
  },
  {
    Name: "🎓 University of Virginia (UVA)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 5:00 PM (EST)",
    Notes: "By this date",
  },
  {
    Name: "🎓 University of Virginia (UVA)",
    Tag: "EA",
    Confirmed: "Approximate",
    "Decision Date": "February 15, 2025",
    Notes: "By this date",
  },
  {
    Name: "🎓 University of Virginia (UVA)",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 University of Washington (UDub)",
    Tag: "RD",
    Confirmed: "Approximate",
    "Decision Date": "March 1, 2025 → March 15, 2025",
    Notes: "",
  },
  {
    Name: "🎓 UT Austin",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 15, 2025",
    Notes: "",
  },
  {
    Name: "🎓 UT Austin",
    Tag: "RD",
    Confirmed: "Approximate",
    "Decision Date": "February 15, 2025",
    Notes: "",
  },
  {
    Name: "🎓 Vanderbilt University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Villanova University",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "November 25, 2024",
    Notes: "",
  },
  {
    Name: "🎓 Washington and Lee",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 8:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Washington University in St. Louis (WashU)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 12, 2024",
    Notes: "In the evening (Central Time)",
  },
  {
    Name: "🎓 Washington University in St. Louis (WashU)",
    Tag: "ED 2",
    Confirmed: "Approximate",
    "Decision Date": "February 14, 2025",
    Notes: "In the evening (Central Time)",
  },
  {
    Name: "🎓 Wellesley College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 7, 2024 10:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Wellesley College",
    Tag: "ED 2",
    Confirmed: "Speculated",
    "Decision Date": "February 8, 2025 10:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Wellesley College",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 15, 2025 10:00 AM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 William & Mary",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 10, 2024 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Williams College",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024",
    Notes: "In the evening (Eastern Time)",
  },
  {
    Name: "🎓 Williams College",
    Tag: "RD",
    Confirmed: "Speculated",
    "Decision Date": "March 21, 2025 6:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Worcester Polytechnic Institute (WPI)",
    Tag: "ED",
    Confirmed: "Confirmed",
    "Decision Date": "December 13, 2024 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Worcester Polytechnic Institute (WPI)",
    Tag: "EA",
    Confirmed: "Confirmed",
    "Decision Date": "January 16, 2025 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Yale University",
    Tag: "REA/SCEA",
    Confirmed: "Confirmed",
    "Decision Date": "December 17, 2024 5:00 PM (EST)",
    Notes: "",
  },
  {
    Name: "🎓 Yale University",
    Tag: "RD",
    Confirmed: "Confirmed",
    "Decision Date": "March 27, 2025 7:00 PM (EST)",
    Notes: "",
  },
];
